name: Deploy Docs
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - shell: bash
        run: |
          echo "1.0.`date +%s`" > version.txt
      - name: Upload version artifact
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: version.txt
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(cat version.txt)
      - name: Build and publish docker image - <%= PAYMENT_NAME %> <%= ECOMMERCE_NAME %>
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: docs-storefrontcloud-io/v2-payment-<%= PAYMENT_TAG %>-<%= ECOMMERCE_TAG %>:${{ steps.get_version.outputs.VERSION }}
          registry: registry.storefrontcloud.io
          username: ${{ secrets.DOCS_CLOUD_USERNAME }}
          password: ${{ secrets.DOCS_CLOUD_PASSWORD }}
          workdir: packages/<%= ECOMMERCE_TAG %>/docs
          dockerfile: ../../../.vuestorefrontcloud/docker/docs-<%= ECOMMERCE_TAG %>/Dockerfile
          buildoptions: "--compress"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download version artifact
        uses: actions/download-artifact@v2
        with:
          name: version
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(cat version.txt)
      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: https://docs.europe-west1.gcp.storefrontcloud.io/v1
          environment: production
          initial_status: in_progress
      - name: Deploy on docs.europe-west1.gcp.storefrontcloud.io/<%= PAYMENT_TAG %>/<%= ECOMMERCE_TAG %>
        id: publish
        uses: vuestorefront/publish-docs-action@main
        with:
          user-id: ${{ secrets.DOCS_CLOUD_USERNAME }}
          api-key: ${{ secrets.DOCS_CLOUD_PASSWORD }}
          name: "docs-v2-payment-<%= PAYMENT_TAG %>-<%= ECOMMERCE_TAG %>"
          tag: "${{ steps.get_version.outputs.VERSION }}"
          image: "registry.storefrontcloud.io/docs-storefrontcloud-io/v2-payment-<%= PAYMENT_TAG %>-<%= ECOMMERCE_TAG %>"
          path: "/<%= PAYMENT_TAG %>/<%= ECOMMERCE_TAG %>"
          port: "80"
          has-base-path: true
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://docs.europe-west1.gcp.storefrontcloud.io/
          state: "success"
          description: Congratulations! The deploy is done.
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://docs.europe-west1.gcp.storefrontcloud.io/v1
          description: Unfortunately, the instance hasn't been updated.
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
