name: Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install -g npm-cli-login
          npm-cli-login -u ${{ secrets.CLOUD_USERNAME }} -p ${{ secrets.CLOUD_PASSWORD }} -e ${{ secrets.NPM_EMAIL }} -r https://registrynpm.storefrontcloud.io
          yarn --frozen-lockfile
        if: |
          steps.cache-yarn-cache.outputs.cache-hit != 'true' ||
          steps.cache-node-modules.outputs.cache-hit != 'true'
      - name: Build and run tests
        run: yarn build && yarn test
